### ISSUE TITLE
Cannot find module 'dayjs/plugin/localeData' (v1.9.2)

### ISSUE THREAD

**Issue by ntzyz** [iamkun/dayjs#1135]
**Describe the bug**

The following code just crash:
```
const dayjs = require('dayjs')
dayjs.extend(require('dayjs/plugin/localeData'))
```

Error:
```
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'dayjs/plugin/localeData'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1222:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:446:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:74:3)
    at internal/main/repl.js:19:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

**Expected behavior**
No error should happen

**Information**
 - Day.js Version [e.g. v1.9.2]
 - OS: [e.g. macOS]
 - Browser [e.g. nodejs v14]

**Comment by iamkun** [comment]
same bug #1132, will fix soon

**Comment by iamkun** [comment]
v1.9.3 has fixed this bug. Sorry for the inconvenience.

**Comment by gardmkdg1** [comment]
https://raw.githubusercontent.com/Haeresis/NodeAtlas/gh-pages/v1.x/README.en.md

**Comment by spsaucier-bakkt** [comment]
I'm still having this issue in v1.9.4.
