### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by krvstianeq** [iamkun/dayjs#1244]
Hello. I use day.js for my Discord bot, it seems to work, but after some time it gives me this error:

```
RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at e (/home/container/node_modules/dayjs/plugin/duration.js:1:499)
    at d.i.add (/home/container/node_modules/dayjs/plugin/duration.js:1:3501)
    at d.i.add (/home/container/node_modules/dayjs/plugin/duration.js:1:3542)
    at d.i.add (/home/container/node_modules/dayjs/plugin/duration.js:1:3542)
    at d.i.add (/home/container/node_modules/dayjs/plugin/duration.js:1:3542)
    at d.i.add (/home/container/node_modules/dayjs/plugin/duration.js:1:3542)
    at d.i.add (/home/container/node_modules/dayjs/plugin/duration.js:1:3542)
    at d.i.add (/home/container/node_modules/dayjs/plugin/duration.js:1:3542)
    at d.i.add (/home/container/node_modules/dayjs/plugin/duration.js:1:3542)
```

How to fix this issue?

**Comment by iamkun** [comment]
Any detail, please? Like, how do you use this plugin?

And might be related to this bug #1214

**Comment by krvstianeq** [comment]
``
const dayjs = require("dayjs");
const duration = require('dayjs/plugin/duration');
const relativeTime = require('dayjs/plugin/relativeTime');
require('dayjs/locale/pl');

dayjs.extend(duration);
dayjs.extend(relativeTime);
await message.channel.send(`Bot uptime: ${dayjs.duration(client.uptime).locale('pl').humanize()}`)
``

**Comment by iamkun** [comment]
Can you please check if this line `dayjs.extend(duration);` is excited too many times in your logic?

**Comment by krvstianeq** [comment]
I think `dayjs.extend(duration);` line is excited every command use, so I think it is caused by too many use.

Can `extend` function be used globally?

**Comment by iamkun** [comment]
I believe the extend bug is fixed in #1214, and will be available in the next release. 

Also, you can update your own logic to use it only at the bootstrap of the APP.

**Comment by krvstianeq** [comment]
How can I implement fix from #1214 ?

**Comment by iamkun** [comment]
not #1214, what I mean is, you can move this `extend` logic to an upper scope in your own project.

**Comment by krvstianeq** [comment]
what do you mean
