### ISSUE TITLE
 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by void-soul** [iamkun/dayjs#1250]
Hello. I use day.js(1.9.1) for my ERP, it works nice, but after some time it gives me this error:
`Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2721)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2903)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2903)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2903)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2903)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2903)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2903)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2903)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2903)
    at d.o.parse (/data/services/dmce-erp/service-dist/node_modules/dayjs/plugin/customParseFormat.js:1:2903)
`
How to fix this issue?

**Comment by iamkun** [comment]
might relate to #1214
