### ISSUE TITLE
Custom plugins break jest tests?

### ISSUE THREAD

**Issue by lachlansleight** [iamkun/dayjs#1365]
**Describe the bug**
I have a custom plugin which provides a custom formatting option to be used like `const example = dayjs().weeklogWeek()`

It works fine with typescript completion and stuff, but when I run a jest spec that uses any component using this plugin, I get the following output:

```js
 FAIL  components/pages/__tests__/SingleEntry.spec.tsx
  ● Test suite failed to run

   path\to\file\weeklogFormat.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import dayjs from 'dayjs'
                                                                                                    ^^^^^

    SyntaxError: Unexpected identifier

      1 | import dayjs from 'dayjs';
    > 2 | import weeklogFormat from '../../lib/plugins/weeklogFormat'
        | ^
      3 | dayjs.extend(weeklogFormat);
      4 | import EntryBlock, { EntryBlockEntry } from "../EntryBlock";
      5 | 

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1258:14)
      at Object.<anonymous> (components/entries/EntryWeek.tsx:2:1)
```

Which is kind of perplexing to me. The test works fine if I'm using a built-in module.

This is my plugin script (weeklogFormat.js) - where `getWeeklogWeek` is just a big function that takes in a dayjs object and spits out a new object - it works fine outside of the spec:

```js
const weeklogWeek = (o, c) => {
    const proto = c.prototype;
    proto.weeklogWeek = function() { 
        return getWeeklogWeek(this);
     }
}

export default weeklogWeek;
```

This is my typescript definition for the plugin:

```js
import { PluginFunc } from 'dayjs'

declare const plugin: PluginFunc

declare module 'dayjs' {
    interface Dayjs {
        weeklogWeek(): {
            year: number,
            month: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11,
            week: 1 | 2 | 3 | 4 | 5,
            day: 1 | 2 | 3 | 4 | 5 | 6 | 7,
            prettyString: string
        }
    }
}

export = plugin;
```

And this is the testing spec:

```js
import dayjs from 'dayjs';
import weeklogFormat from '../weeklogFormat';
dayjs.extend(weeklogFormat);

describe("Weeklog Week Formatting", () => {
    it("Correctly formats non-edge-cases", () => {
        const d = dayjs("14/01/2021", "DD/MM/YYYY").weeklogWeek();
        expect(d.year).toBe(2021);
        expect(d.month).toBe(0);
        expect(d.week).toBe(1);
        expect(d.day).toBe(3);
        expect(d.prettyString).toBe("January Week 2");
    })
});
```

**Expected behavior**
I would have expected the custom plugin to be imported successfully during testing in the same way as it is during normal execution - like inbuilt dayjs plugins are. I wonder whether there's some tsconfig, babelrc or jestconfig shenanigans that need to happen, but I'm a little inexperienced with that whole side of things. :c

**Information**
 - Day.js Version: 1.9.8
 - OS: Windows 10 1909
 - Browser: Brave 1.19.86 Chromium 88.0.4324.96
 - Time zone: GMT +11

I should also say that this is happening within a TypeScript Next.js app

**Comment by lachlansleight** [comment]
Alright in desperation I tried a thing that I didn't really understand and it worked!

In jest.config, I changed 

```js
transform: {
    "^.+\\.(ts|tsx)$": "babel-jest",
}
```

to 

```js
transform: {
    "^.+\\.(ts|tsx|js|jsx)$": "babel-jest",
}
```

And that's fixed the problem
