### ISSUE TITLE
error: Uncaught TypeError: Cannot set property 'dayjs' of undefined

### ISSUE THREAD

**Issue by remdragon** [iamkun/dayjs#1461]
I'm just trying to get started using dayjs using deno 1.9.0. I've downloaded dayjs 1.10.4 using the link the instructions gave me.

Here is my test file calendar.js:
```
//import * as dayjs from "https://cdn.jsdelivr.net/npm/dayjs@1.10.4/dayjs.min.js"
import * as dayjs from "./dayjs.js"

let now = dayjs()
console.log ( now )
```

And here's what I get when I run "deno run calendar.js":
```
error: Uncaught TypeError: Cannot set property 'dayjs' of undefined
    at file:///[SNIP]/testing/dayjs.js:1:143
    at file:///[SNIP]/testing/dayjs.js:1:148
```

Unfortunately since dayjs has been minified, I don't know how to begin to troubleshoot this even further, especially since this is my first attempt to use the library. Am I importing it or doing something else wrong?

**Comment by MrPoketes** [comment]
Try doing

```
import dayjs from "dayjs"
let now = dayjs()
console.log(now)
```

Should work

**Comment by remdragon** [comment]
Thank you for the suggestion, but I still can't get it to work:

import dayjs from "dayjs"
error: relative import path "dayjs" not prefixed with / or ./ or ../
Imported from "file:///[SNIP]/calendar.js"

import dayjs from "./dayjs.js"
error: Uncaught SyntaxError: The requested module './dayjs.js' does not
provide an export named 'default'
import dayjs from "./dayjs.js"

import dayjs from ***@***.***/dayjs.min.js"
error: Uncaught SyntaxError: The requested module '
***@***.***/dayjs.min.js' does not provide an
export named 'default'
import dayjs from ***@***.***/dayjs.min.js"

**Comment by harvanchik** [comment]
I'm getting the same errors.

**Comment by bhutiyakishan1** [comment]
@iamkun  Any updates to this issue? Even i am getting the same errors when using typescript.

**Comment by bhutiyakishan1** [comment]
@remdragon Did you end up finding any solution to this?

**Comment by remdragon** [comment]
I did not. I ended up developing my own lightweight date management object.


Royce Mitchell, IT Consultant
ITAS Solutions
***@***.***

There are three hard problems in computer science: naming things, and
off-by-one errors.

**Comment by shotrifork** [comment]
You can import it using:
`import dayjs from "https://cdn.skypack.dev/dayjs";`

**Comment by raviteja83** [comment]
@shotrifork Above is not working with recent version.  Getting this error - [cdn.skypack.dev/error/build:dayjs@v1.11.1-hjNPZCmDt5LAsgqX8MmQ](https://cdn.skypack.dev/error/build:dayjs@v1.11.1-hjNPZCmDt5LAsgqX8MmQ)

**Comment by cdoremus** [comment]
This works (in Deno repl):
```
> import dayjs from "https://esm.sh/dayjs@v1.11.3";
undefined
> dayjs('2018-08-08')
u {
  "$L": "en",
  "$d": 2018-08-08T04:00:00.000Z,
  "$x": {},
  "$y": 2018,
  "$M": 7,
  "$D": 8,
  "$W": 3,
  "$H": 0,
  "$m": 0,
  "$s": 0,
  "$ms": 0
}
```
You can also use skypack to import dayjs:
```
import dayjs from "https://cdn.skypack.dev/dayjs@v1.11.3?dts"
```
