### ISSUE TITLE
Cannot set property '$timezone' of undefined

### ISSUE THREAD

**Issue by herenickname** [iamkun/dayjs#1584]
Exception:
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError: Cannot set property '$timezone' of undefined
    at M.f.tz (/root/v3/node_modules/dayjs/plugin/timezone.js:1:1271)
    at Function.withdrawalCompleted (/root/v3/dist/core/common/utils/TelegramNotification.js:31:54)
    at EventEmitter.<anonymous> (/root/v3/dist/core/withdrawal/services/status.service.js:124:63)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Code (withdrawalCompleted):
```ts
import * as DayJS from 'dayjs'
import * as DayJSTimezone from 'dayjs/plugin/timezone'

DayJS.extend(DayJSTimezone)
const dateText = DayJS(withdrawal.createdAt).tz('Europe/Moscow').format('dd.LL.yyyy HH:mm:ss ZZZZ')
```

**Comment by mandaputtra** [comment]
Do you use Typescript ? If yes. Enable [esmodule interop](https://www.typescriptlang.org/tsconfig#esModuleInterop)

```
// tsconfig.json
{
    "extends": "fastify-tsconfig",
    "compilerOptions": {
        "outDir": "dist",
        "esModuleInterop": true
    },
    "include": ["src/**/*.ts"]
}
```

and just use it like this

```
import DayJS from 'dayjs'
import DayJSTimezone from 'dayjs/plugin/timezone'

DayJS.extend(DayJSTimezone)

export class Notification {
     public static async withdrawalCompleted(withdrawal) {
        const dateText = DayJS(withdrawal.createdAt).tz('Europe/Moscow').format('dd.LL.yyyy HH:mm:ss ZZZZ')
        ...
    }
}
```

**Comment by mngu** [comment]
Having the same problem here, even with `esModuleInterop: true`

**Comment by mngu** [comment]
Ok, Timezone plugin depends on Utc, don't forget to add it as well !
```javascript
import DayJS from 'dayjs'
import DayJSUtc from 'dayjs/plugin/utc'
import DayJSTimezone from 'dayjs/plugin/timezone'

DayJS.extend(DayJSUtc)
DayJS.extend(DayJSTimezone)
```

**Comment by jonluca** [comment]
Same here -

**Comment by iamkun** [comment]
First of all, please extend UTC plugin first

> Ok, Timezone plugin depends on Utc, don't forget to add it as well!

Second, if you still facing some trouble, feel free to reply here with a demo. (https://npm.runkit.com/dayjs)

**Comment by Dilshan97** [comment]
> Ok, Timezone plugin depends on Utc, don't forget to add it as well !
> 
> ```js
> import DayJS from 'dayjs'
> import DayJSUtc from 'dayjs/plugin/utc'
> import DayJSTimezone from 'dayjs/plugin/timezone'
> 
> DayJS.extend(DayJSUtc)
> DayJS.extend(DayJSTimezone)
> ```

it's working after adding the UTC plugin
