### ISSUE TITLE
core bug with locale plugin

### ISSUE THREAD

**Issue by titanism** [iamkun/dayjs#2281]
```js
> dayjs('4/23/22', 'M/DD/YY').locale('en').format('LT')
'12:00 AM'
> dayjs('4/23/22', 'M/DD/YY').locale('en').format('LTS')
'12:00:00 AM'
> dayjs('4/23/22', 'M/DD/YY').locale('en').format('L')
'04/23/2022'
> dayjs('4/23/22', 'M/DD/YY').locale('en').format('LL')
'April 23, 2022'
> dayjs('4/23/22', 'M/DD/YY').locale('en').format('LLL')
'April 23, 2022 12:00 AM'
> dayjs('4/23/22', 'M/DD/YY').locale('en').format('LLLL')
'Saturday, April 23, 2022 12:00 AM'
> dayjs('4/23/22', 'M/DD/YY').locale('en').format('l')
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at /Users/user/Projects/web/node_modules/.pnpm/dayjs@1.11.7/node_modules/dayjs/plugin/localizedFormat.js:1:676
    at String.replace (<anonymous>)
    at /Users/user/Projects/web/node_modules/.pnpm/dayjs@1.11.7/node_modules/dayjs/plugin/localizedFormat.js:1:563
    at r.format (/Users/user/Projects/web/node_modules/.pnpm/dayjs@1.11.7/node_modules/dayjs/plugin/localizedFormat.js:1:761)
    at e.format (/Users/user/Projects/web/node_modules/.pnpm/dayjs@1.11.7/node_modules/dayjs/plugin/preParsePostFormat.js:1:592)
    at u.format (/Users/user/Projects/web/node_modules/.pnpm/dayjs@1.11.7/node_modules/dayjs/plugin/utc.js:1:1655)
> dayjs('4/23/22', 'M/DD/YY').locale('zh').format('l')
'2022/4/23'
> dayjs('4/23/22', 'M/DD/YY').locale('de').format('l')
'23.4.2022'
```

As you can see, there is an uncaught typeerror above for "l", "ll", "lll", and "llll" usage for certain locales, e.g. `en`.

**Comment by tendguo** [comment]
> The reason is because the `englishFormats` object does not contain it.
> 
> https://github.com/iamkun/dayjs/blob/00c223b7e92970d07557133994fcb225a6d4c960/src/plugin/localizedFormat/utils.js#L5-L12
> 
> Needs to have `l`, `ll`, `lll`, and `llll` added. Will submit a PR now.
I don't agree with your conclusion, because I looked up the source code and found this
`const B = b && b.toUpperCase()`

**Comment by tendguo** [comment]
> 

I don't agree with your conclusion, because I looked up the source code and found this
```
const B = b && b.toUpperCase()
return a || formats[b] || englishFormats[b] || t(formats[B])
```

**Comment by iamkun** [comment]
there should be no problem with localizedFormat plugin

https://runkit.com/embed/yzvddg5czfg6

**Comment by tomastan** [comment]
This still looks to be an issue in 1.11.13:
![image](https://github.com/user-attachments/assets/9625efa3-b778-4558-bb5f-c14402f9fc57)

**Comment by TheDutchCoder** [comment]
> there should be no problem with localizedFormat plugin
> 
> https://runkit.com/embed/yzvddg5czfg6

This is indeed still a real bug.

Weirdly enough it only happen for us when used as a Nuxt plugin, not when used as a singleton (but that's problematic due to cross-request sharing).

**Comment by titanism** [comment]
Yeah still 100% a bug that we clearly showed how to reproduce but is not resolved and ignored.
