### ISSUE TITLE
dayjs 1.11.10 TypeError: o(...).tz is not a function

### ISSUE THREAD

**Issue by joshzcold** [iamkun/dayjs#2455]
**Describe the bug**

We started hitting a stack trace while using the latest dayjs for testing.

```
TypeError: o(...).tz is not a function
    at o.tz (webpack:///./node_modules/dayjs/plugin/timezone.js:1:1745)
```
We are calling `.tz` like this
```ts
import dayjs from "dayjs";
import utc from "dayjs/plugin/utc"
import timezone from "dayjs/plugin/timezone"

// Enable timezone in dayjs
dayjs.extend(timezone)
dayjs.extend(utc)
const finishDateUtc = dayjs.tz(scan.finishDate, "utc").format("YYYY-MM-DD HH_mm_ss")
```

Reverting back to `1.11.9` solves the issue. 

**Expected behavior**

`.tz` is a callable function 

**Information**
 - Day.js Version: 1.11.10
 - OS: Ubuntu 22 Linux
 - Browser: Chrome v117
 - Time zone: utc

**Comment by joshzcold** [comment]
Stack trace
```
at o.tz ([webpack:///./node_modules/dayjs/plugin/timezone.js:1:1745](https://10.38.10.251/__/#))
    at Context.eval ([webpack:///./cypress/tests/e2e/customer/perimeter-scan/C1434-reports-scan-results.cy.ts:154:31](https://10.38.10.251/__/#))
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (https://10.38.10.251/__cypress/runner/cypress_runner.js:3486:19)
    at Promise._then (https://10.38.10.251/__cypress/runner/cypress_runner.js:1239:17)
    at Promise.then (https://10.38.10.251/__cypress/runner/cypress_runner.js:1132:17)
    at CommandQueue.runCommand (https://10.38.10.251/__cypress/runner/cypress_runner.js:143427:8)
    at next (https://10.38.10.251/__cypress/runner/cypress_runner.js:143627:19)
    at <unknown> (https://10.38.10.251/__cypress/runner/cypress_runner.js:143648:16)
    at tryCatcher (https://10.38.10.251/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (https://10.38.10.251/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (https://10.38.10.251/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (https://10.38.10.251/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (https://10.38.10.251/__cypress/runner/cypress_runner.js:1701:18)
    at <unknown> (https://10.38.10.251/__cypress/runner/cypress_runner.js:2392:25)
    ```

**Comment by joshzcold** [comment]
`scan.finishDate` is an object 

![image](https://github.com/iamkun/dayjs/assets/36175703/6e3bf4ac-668d-403f-92b0-b04fc819dce9)

Ill try to recreate in the reproduce script

parse a regular string like `2023-04-28` is working

**Comment by joshzcold** [comment]
This seems un-reproducible in isolation. Some mixture of promises within cypress is needed to reproduce.
