### ISSUE TITLE
Load locale without the need of a global instance

### ISSUE THREAD

**Issue by qwerty287** [iamkun/dayjs#2516]
Hello,

I'm working on a web project using `dayjs` which should load locales dynamically (using `await import('<locale path>');`) from the `locales` folder of `dayjs`.
However, these files need an instance of `dayjs` available as global object, in my case I need to set `window.dayjs` which is pretty ugly.
Is there a way to load the locale and directly specify the `dayjs` instance it should use?

Thanks!

Possibly related: https://github.com/iamkun/dayjs/issues/655

**Comment by jsjames** [comment]
Hi - Has anyone been able to find a solution for this.  I am dynamically importing the locale file (vite setup) but get the following errror:

fr.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'locale')
    at fr.js:1:1162
    at fr.js:1:232
    at fr.js:1:243

The line `dayjs.locale(locale, null, true)` is where the issue is happening.  Is there some nuance to the vite import where it does not find the `import dayjs from 'dayjs'` as the top of the file?
