### ISSUE TITLE
Format to name of day, week, month: "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by jinusean** [iamkun/dayjs#2523]
**Describe the bug**
Formatting datetime with name of week, name of month, etc. throws an error.

```javascript
dayjs().format('ddd')

TypeError: Cannot read properties of undefined (reading '4')
    at h (/Users/suah/Projects/Javascripts/tcl/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/dayjs.min.js:1:5023)
    at /Users/suah/Projects/Javascripts/tcl/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/dayjs.min.js:1:5544
    at /Users/suah/Projects/Javascripts/tcl/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/dayjs.min.js:1:5920
    at String.replace (<anonymous>)
    at M.m.format (/Users/suah/Projects/Javascripts/tcl/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/dayjs.min.js:1:5160)
    at M.u.format (/Users/suah/Projects/Javascripts/tcl/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/plugin/utc.js:1:1655)
    at /Users/suah/Projects/Javascripts/tcl/packages/common/tests/date/comparator.test.ts:27:25
    at file:///Users/suah/Projects/Javascripts/tcl/node_modules/.pnpm/@vitest+runner@0.34.6/node_modules/@vitest/runner/dist/index.js:135:14
    at file:///Users/suah/Projects/Javascripts/tcl/node_modules/.pnpm/@vitest+runner@0.34.6/node_modules/@vitest/runner/dist/index.js:58:26
    at runTest (file:///Users/suah/Projects/Javascripts/tcl/node_modules/.pnpm/@vitest+runner@0.34.6/node_modules/@vitest/runner/dist/index.js:663:17)
```

**Expected behavior**
Should return a string with the name of the week.

**Information**
 - Day.js Version 1.11.10
 - OS: Mac 13.4.1

**Comment by kavish5** [comment]
@jinusean Can you please add more details on what exactly your code was? I had checked that on Windows and it is working well. Not denying it could not be an issue on Mac, but would like more details like if it was happening on a specific scenario or step to reproduce, if it was on any specific locale, expected output, etc. More the details, easier it would be to check and recreate.
