### ISSUE TITLE
Named export 'Dayjs' not found. The requested module 'dayjs' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by gorayaa66** [iamkun/dayjs#2576]
**Describe the bug**
After upgrading Svelte from 3.5 to 4 and SvelteKit from 1.5.0 to 2, I encountered this error when using dayjs: Named export 'Dayjs' not found. The requested module 'dayjs' is a CommonJS module, which may not support all module.exports as named exports, i tried updating dayjs version after deleting node_modules and package-lock.json but nothing work. Below is the bug log:

**Bug log**
Named export 'Dayjs' not found. The requested module 'dayjs' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'dayjs';
const {Dayjs} = pkg;

    at analyzeImportedModDifference (file:///Users/apple/Documents/svelte%20projects/appName-S/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54798:19)
    at nodeImport (file:///Users/apple/Documents/svelte%20projects/appName-S/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54749:9)
    at async ssrImport (file:///Users/apple/Documents/svelte%20projects/appName-S/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54644:24)
    at async eval (eval at instantiateModule (file:///Users/apple/Documents/svelte%20projects/appName-S/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54703:28), <anonymous>:3:44)
    at async instantiateModule (file:///Users/apple/Documents/svelte%20projects/appName-S/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:54706:9)

**Expected behavior**
Dayjs functions and everything is working but getting this error.

**Information**
 - Day.js Version 1.11.7
 - OS: Mac

**Comment by gorayaa66** [comment]
changed from
import { Dayjs } from 'dayjs'
to
import { type Dayjs } from 'dayjs'
type keyword was missing which was causing the issue.
