### ISSUE TITLE
Failed test for diff method 

### ISSUE THREAD

**Issue by dyoshikawa** [iamkun/dayjs#970]
**Describe the bug**

```
yarn jest ./test/display.test.js
```

Output:

```
  ● Difference › diff -> in seconds, minutes, hours, days, weeks, months, quarters, years 

    expect(received).toBe(expected) // Object.is equality
    
    Expected value to be:
      32.86666666666667
    Received:
      32.87096774193548

      190 |       expect(dayjsA.diff(dayjsB, unit, true)).toBe(momentA.diff(momentB, unit, true))
      191 |       expect(dayjsA.diff(dayjsC, unit)).toBe(momentA.diff(momentC, unit))
    > 192 |       expect(dayjsA.diff(dayjsC, unit, true)).toBe(momentA.diff(momentC, unit, true))
      193 |     })
      194 |   })
      195 | 
      
      at forEach (test/display.test.js:192:47)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/display.test.js:188:11)
```

**Expected behavior**

Result of dayjs equals result of moment.js.

**Information**
 - Day.js Version: v1.8.30 master branch
 - OS: Mac OSX Catalina
 - Browser: None. Node.js v14.5.0 
 - Time zone: Asia/Tokyo +9:00

**Comment by iamkun** [comment]
Seems ok on my side `npx jest ./test/display.test.js`, even if I change my tz to +9:00

**Comment by dyoshikawa** [comment]
Thanks.
I retried it today, then the test was passed.
I don't understand reason of last failure.

If it is occur again, I report it.
